version: "3.8"

services:
  # Gradio Interface
  gradio-app:
    build:
      context: ./apps/02_gradio_interface
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - MODEL_PATH=/app/models/yolo11n.pt
      - GRADIO_SERVER_NAME=0.0.0.0
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    depends_on:
      - model-downloader
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Streamlit Dashboard
  streamlit-app:
    build:
      context: ./apps/03_streamlit_webapp
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    depends_on:
      - model-downloader
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # FastAPI Service
  fastapi-app:
    build:
      context: ./apps/04_fastapi_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=info
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    depends_on:
      - model-downloader
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Jupyter Environment
  jupyter-lab:
    build:
      context: ./apps/06_jupyter_environment
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=yolo-course-2024
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./models:/home/jovyan/models:ro
      - ./data:/home/jovyan/data
    depends_on:
      - model-downloader
    restart: unless-stopped

  # Model Downloader (Init Container)
  model-downloader:
    build:
      context: ./scripts
      dockerfile: Dockerfile.model-downloader
    volumes:
      - ./models:/app/models
    command: python download_models.py
    restart: "no"

  # External YOLO Service
  yolo-service:
    image: johannestang/yolo_service:1.0-yolov3_coco
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ui"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Nginx Load Balancer (Optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - gradio-app
      - streamlit-app
      - fastapi-app
    restart: unless-stopped

volumes:
  models_data:
    driver: local
  app_data:
    driver: local

networks:
  yolo-network:
    driver: bridge
